import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { useMutation, useQuery } from "react-query";
import { getPedidos } from "~/api/querys";
import { postPedidos } from "~/api/mutations";

import { string } from "zod";

const Home: NextPage = () => {

  const { data, isLoading, isError } = useQuery("pedidos", getPedidos);

  // const mutation = useMutation(postPedidos({nome: "marcelo", valor: 15}));
  const mutation = useMutation(postPedidos);


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Zambas front 
          </h1>

          <button onClick={()=>mutation.mutate({nome: "oi", valor: 10})}>oi</button>
        </div>
      </main>
    </>
  );
};

export default Home;
